In [9]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_curve

In [10]:
iris = datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.25, random_state = 50)

In [11]:
kf = KFold(n_splits=10) #150 is perfectly divisible by 10, 150/10 = 15 samples in each fold.
#1 for testing other for training (made on iris.data pure data without preprocessing)

In [12]:
accuracy_kfold = []
for train_index, test_index in kf.split(iris.data):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train_kf, X_test_kf = iris.data[train_index], iris.data[test_index]
    y_train_kf, y_test_kf = iris.data[train_index], iris.data[test_index]
    #print(X_train.shape, y_train.shape)
    clf_lg_kf = LogisticRegression(random_state = 0)
    clf_lg_kf.fit(X_train, y_train)
    y_pred_kf = clf_lg_kf.predict(X_test)
    accuracy_kfold.append(accuracy_score(y_test, y_pred_kf))

c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/mod

In [13]:
accuracy_kfold

[0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158,
 0.9736842105263158]

ROC (CANCER DATASET) AS ROC WORKS ON BINARY CLASSIFICATION

In [14]:
cancer = datasets.load_breast_cancer()

In [15]:
roc_clf = LogisticRegression(random_state = 0)

In [16]:
X_train_roc, X_test_roc, y_train_roc, y_test_roc = train_test_split(cancer.data, cancer.target, test_size=0.3, random_state = 50)

In [17]:
roc_clf.fit(X_train_roc, y_train_roc)

c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [18]:
roc_y_score = roc_clf.predict(X_test_roc)

In [19]:
accuracy_score(y_test_roc, roc_y_score)

0.9473684210526315

In [20]:
fpr, tpr, thresholds = roc_curve(y_test_roc, roc_y_score, pos_label=2)

c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_ranking.py:949: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn("No positive samples in y_true, "


In [21]:
fpr

array([0.        , 0.66081871, 1.        ])

In [22]:
tpr

array([nan, nan, nan])

In [23]:
thresholds

array([2, 1, 0])